=== anushgs/Lab_programs-Lab_01/upcomingMeeting.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="meetings_info">
<xs:complexType>
<xs:sequence>
<xs:element name="upcomming_meeting" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>
<xs:element name="title" type="xs:string"></xs:element>
<xs:element name="date" type="xs:date"></xs:element>
<xs:element name="description" type="xs:string"></xs:element>
<xs:element name="duration" type="xs:string"></xs:element>
<xs:element name="total_attendees" type="attendees"></xs:element>
<xs:element name="platform" type="platform_type"></xs:element>
<xs:element name="link" type="xs:string"></xs:element>
<xs:element name="created_by" type="xs:string"></xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:simpleType name="attendees">
<xs:restriction base="xs:integer">
<xs:minInclusive value="2"></xs:minInclusive>
<xs:maxInclusive value="50"></xs:maxInclusive>
</xs:restriction>
</xs:simpleType>
<xs:simpleType name="platform_type">
<xs:restriction base="xs:string">
    <xs:enumeration value="Gmeet"/>
    <xs:enumeration value="Zoom"/>
    <xs:enumeration value="WebEx"/>
</xs:restriction>
</xs:simpleType>
</xs:schema>

=== anushgs/Lab_programs-Lab_01/upcomingMeeting.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="upcomingMeeting.xsl"?>
<meetings_info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="upcomingMeeting.xsd">
  <upcomming_meeting>
    <title>Status update</title>
    <date>2021-12-19</date>
    <description>This meeting was created as per request of the client</description>
    <duration>60 mins</duration>
    <total_attendees>10</total_attendees>
    <platform>Gmeet</platform>
    <link>https://meet.google.com/</link>
    <created_by>Kiran Kumar </created_by>
  </upcomming_meeting>
  <upcomming_meeting>
    <title>Genreal Discuusion</title>
    <date>2021-12-16</date>
    <description>This meeting was created by the lead to discuss daily goals</description>
    <duration> 20 mins</duration>
    <total_attendees>15</total_attendees>
    <platform>Zoom</platform>
    <link>https://zoom.us/</link>
    <created_by>Ravi kumar </created_by>
  </upcomming_meeting>
  <upcomming_meeting>
    <title>Feature updates</title>
    <date>2021-12-21</date>
    <description>This meeting was created by the lead to discuss about feature updates</description>
    <duration> 30 mins</duration>
    <total_attendees>15</total_attendees>
    <platform>WebEx</platform>
    <link>https://www.webex.com/</link>
    <created_by>Sam Pinto </created_by>
  </upcomming_meeting>
  <upcomming_meeting>
    <title>Review Meeting</title>
    <date>2021-12-22</date>
    <description>This meeting is to review the progress</description>
    <duration> 20 mins</duration>
    <total_attendees>5</total_attendees>
    <platform>WebEx</platform>
    <link>https://www.webex.com/</link>
    <created_by>Arun Lobo </created_by>
  </upcomming_meeting>
  <upcomming_meeting>
    <title>Weekly reporting</title>
    <date>2021-12-28</date>
    <description>Meeting conducted weekly to discuss the progress</description>
    <duration> 30 mins</duration>
    <total_attendees>15</total_attendees>
    <platform>WebEx</platform>
    <link>https://www.webex.com/</link>
    <created_by>Arun Lobo </created_by>
  </upcomming_meeting>
</meetings_info>
